# Generated by Django 3.0.4 on 2022-07-14 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('round', models.IntegerField()),
                ('question_no', models.IntegerField()),
                ('answer', models.CharField(max_length=40)),
                ('file_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('user_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(default=0)),
                ('seq_no', models.IntegerField(default=0)),
                ('answers', models.CharField(max_length=40)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.User')),
            ],
        ),
    ]
