# Generated by Django 4.0.6 on 2022-07-15 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
