# Generated by Django 4.0.6 on 2022-07-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_test_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='super_user',
            field=models.BooleanField(default=False),
        ),
    ]
