# Generated by Django 3.2.14 on 2022-07-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_user_super_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='answers',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
